### ISSUE TITLE
Updating Atomic Red Team's lookup

### ISSUE THREAD

**Issue by soladev** [dlamspl/splunk_attack_range_reporting#11]
Hi, 

I'm using Splunk Attack Range and I noticed that the lookup for Atomic Red Team tests for the "Attack Range Navigator" dashboard is out-of-date by two years. 

Do you have any plans to update it and/or does the main Attack Range project have plans to implement an automated upgrade of the lookup (at build time for example)?

**Comment by ccl0utier** [comment]
Yes, @soladev, I will have a look at improving this.  Stay tuned!
